#!/bin/bash

set -o errexit

mkdir -p DownloadSamples

cghub/bin/cgquery -o Query.xml -a "state=live&library_strategy=RNA-Seq&filetype=fasta&sample_type=0*"

rm -rfv DownloadSamples/* CancerTypes/*
python code/ParseCgHubQueryResults.py Query.xml "" DownloadSamples CancerTypes

rm -rf Temp/*

for f in $(pwd)/DownloadSamples/*
do
  sampleID=$(basename $f)
  sampleID=${sampleID/\.xml/}

  if [ -f FeatureCounts/$sampleID ]
  then
    echo $sampleID already processed
    continue
  fi

  if [ -f InProgress/$sampleID ]
  then
    echo $sampleID currently being processed
    continue
  fi

  # This is designed to submit a job to a PBS system, but it could be executed without it.
  qsub $(pwd)/normalize_rnaseq_sample $f
  sleep 60 # Make sure we don't overrun the server
done
