#!/bin/bash

set -o errexit

mkdir -p DownloadSamples DownloadSamples CancerTypes Temp FeatureCounts InProgress

cghub/bin/cgquery -o Query.xml -a "state=live&library_strategy=RNA-Seq&filetype=fasta&sample_type=0*"

rm -rfv DownloadSamples/* CancerTypes/*
python code/ParseCgHubQueryResults.py Query.xml "" DownloadSamples CancerTypes

rm -rf Temp/*

for f in $(pwd)/DownloadSamples/*
do
  sampleID=$(basename $f)
  sampleID=${sampleID/\.xml/}

  if [ -f FeatureCounts/$sampleID ]
  then
    echo $sampleID already processed
    continue
  fi

  if [ -f InProgress/$sampleID ]
  then
    echo $sampleID currently being processed
    continue
  fi

  $(pwd)/normalize_rnaseq_sample $f
done
